name: Java CI with Maven

on:
  push:
    branches:
      - main  # Adjust this to the name of your main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Specify the desired Java version

    - name: Build and Test with Maven
      run: mvn clean verify

